version: '3.8'

networks:
  pv_net:
    driver: bridge
    name: pv_net

services:
  back-end:
    build: ./khoshk
    container_name: back-end
    depends_on:
     db:
       condition: service_healthy
     redis:
       condition: service_healthy
    env_file:
      - ./.env
    networks:
      - pv_net

  db:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: strong-password
      POSTGRES_USER: root
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./khoshk/postgres_data:/var/lib/postgresql/pgdata
    ports:
      - "5435:5432"
    networks:
      - pv_net

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    environment:
      -REDIS_DATABASES: ${REDIS_DB}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./khoshk/redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - pv_net
